name: CI
on:
  push:
    branches: [master]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        emacs_version: [28, "master"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: "18"

      - uses: emacs-eask/setup-eask@master
        with:
          version: "snapshot"

      - name: Print emacs version
        run: |
          emacs --version

      - name: Testing
        env:
          VERSION: ${{ matrix.emacs_version }}
        run: >-
          make docker CMD="make -k link lint"
